### ISSUE TITLE
Crear cuaderno de bitácora

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/hexakiller#1]
Crear cuaderno de bitácora

**Comment by davidvelascogarcia** [comment]
Listo, he documentado la sesión del último día y subido el modelado de las piezas diseñadas.

**Comment by David-Estevez** [comment]
Genial!! Como añadido, podrías poner quién hizo cada cosa para que quede registro de ello.

Por lo demás, yo creo que la issue está más que resuelta!

**Comment by davidvelascogarcia** [comment]
Listo, ya esta actualizado.

**Comment by David-Estevez** [comment]
Perfecto, por mi puedes cerrar la issue ya! :blush:

**Comment by davidvelascogarcia** [comment]
Perfecto, muchas gracias :).
