### ISSUE TITLE
Banco de pruebas: Patas Hexakiller

### ISSUE THREAD

**Issue by davidvelascogarcia** [asrob-uc3m/hexakiller#5]
## Pruebas de estabilidad y resistencia de las patas de Hexakiller

Con el fin de documentar las diversas pruebas de estabilidad y resistencia que se llevarán a cabo en el Hexápodo, abro la issue.

**Comment by davidvelascogarcia** [comment]
Adjunto captura de la versión 1.0 para el banco de pruebas.

![image](https://user-images.githubusercontent.com/29423648/35054073-109f123e-fbac-11e7-8100-a743d1e3aeaa.png)

Figura 1. Pata Hexápodo v1.0

**Comment by David-Estevez** [comment]
Mola, aunque las piezas parecen muy finas para impresión 3D.

Podríamos añadir también una pieza para anclar la pata a algún sitio, ¿Cómo lo ves?

**Comment by davidvelascogarcia** [comment]
Son 3 mm de espesor, debería de poder aguantar el peso de la torreta. De todos modos, se puede probar a imprimir una pequeña o una sección de ella, hacer una pequeña prueba y sino aumentar el espesor.
Sí, habia pensado en los servo horns, los mismos que lleva, que no están en la foto :),(Te lo adjunto).

![imagen](https://user-images.githubusercontent.com/29423648/35214067-3140d236-ff60-11e7-9326-d378c22229c8.png)
Figura 1. Servo Horns

En el servo superior, el conectado al torso, hacer modificaciones al horn y poder sujetarlo con un par de tornillos a la superficie de pruebas.
¿Cómo lo ves?.

**Comment by David-Estevez** [comment]
Para poder avanzar en este proyecto, he diseñado un sencillo banco de pruebas:

![image](https://user-images.githubusercontent.com/1451819/38834638-528b7bde-41c9-11e8-88c7-9fe637ce6c08.png)

Incluye:

* Orange Pi Lite
* 2 servos (pan & tilt)
* Webcam
* Placa controladora de servos
* Placa emuladora de nivel de batería
* Convertidor DC-DC
* Placa de distribución de potencia

La base está impresa en 3D, y las fuentes están subidas a este repo. La documentación llegará según vaya trabajando en él.
